VERSION --use-function-keyword 0.7

DEPS:
    FUNCTION
    ARG --required service
    ARG --required src_files
    BUILD ../../../pkg+deps
    COPY ../../../pkg+artifacts/pkg pkg
    COPY cmd services/$service/cmd
    FOR src IN $src_files
        COPY $src services/$service/$src
    END

COMPILE:
    FUNCTION
    ARG USERARCH
    ARG main_path="cmd/server"
    ARG cgo_enabled=0
    
    RUN cd $main_path && \
        CGO_ENABLED=$cgo_enabled \
        GOARCH=$USERARCH \
	    GOOS=linux \
        go build -o bin/main .
    
    IF [ "$cgo_enabled" = "1" ]
        RUN bash -c "ldd $main_path/bin/main | tr -s [:blank:] '\n' | grep ^/ | xargs -I % install -D % $main_path/%"
        SAVE ARTIFACT $main_path/lib/
        IF [ "$USERARCH" != "arm64" ]
            SAVE ARTIFACT $main_path/usr/
        END
    END

    SAVE ARTIFACT $main_path/bin/main

UNIT_TEST:
    FUNCTION
    ARG coverage_threshold=75.0
    RUN echo $coverage_threshold
    RUN exit 1
    COPY pkg pkg

    RUN go test ./... -coverprofile=coverage-profile.out
    RUN grep -v -i -E 'main.go|pb.go' "coverage-profile.out" > coverage-profile-filtered.out

    LET DISCREPANCY=5.0
    LET LINE_COV=$(go tool cover "-func=coverage-profile.out" | grep total | sed 's/[^0-9\.]*//g' | tr -d '\n')

    IF [ $(echo "$LINE_COV < $coverage_threshold" | bc -l) = 1 ]
        RUN echo "Coverage too low, coverage is $LINE_COV, should be at least $coverage_threshold"
        RUN exit 1
    END
    IF [ $(echo "$LINE_COV > $coverage_threshold + $DISCREPANCY" | bc -l) = 1 ]
        RUN echo "The current coverage $LINE_COV is more than $DISCREPANCY percent greater than the threshold $coverage_threshold. Please adjust the threshold of the service accordingly."
        RUN exit 1
    END

LINT:
    FUNCTION
    ARG FILES_TO_FORMAT=$(gofmt -l ./)
    ARG skip_lint_errors="false"
    IF [ ! -z "$FILES_TO_FORMAT" ]
        RUN echo "Formatting required for:\n$FILES_TO_FORMAT\nRun \"go fmt ./...\" to fix the errors" && exit 1
    END
    RUN golangci-lint run --timeout=5m -j4 ./... || $skip_lint_errors

DOCKER:
    FUNCTION
    ARG UID=1000
    ARG USERARCH
    ARG entry_point="/main"
    ARG workdir=/kp
    ARG cgo_enabled=0
    ARG --required image_tag
    ARG --required service
    ENV TZ=Europe/Berlin
    
    RUN adduser --disabled-password --home "/kp" --uid $UID kp
    RUN chown -R kp:kp /kp

    COPY ../../../services/$service+artifacts/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
    COPY ../../../services/$service+artifacts/zoneinfo /usr/share/zoneinfo
    COPY ../../../services/$service+compile/main /main
    IF [  "$cgo_enabled" = "1" ]
        COPY ../../../services/$service+compile/lib/* /lib
        IF [ "$USERARCH" != "arm64" ]
            COPY ../../../services/$service+compile/usr/* /lib
        END
    END

    USER kp
    WORKDIR $workdir
    ENTRYPOINT "$entry_point"
    SAVE IMAGE $image_tag

RELEASE:
    FUNCTION
    ARG --required image_tag
    SAVE IMAGE --push $image_tag
