version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - asciicheck
    - bodyclose
    - copyloopvar
    - staticcheck
    - unconvert
    - importas
  exclusions:
    paths:
      - pkg/publicapi
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
output:
  format: tab # This is where you set the output format to 'tab'
  sort-results: true # Equivalent to --sort-results
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard # Standard packages.
        - default # Imports that are not standard and not current project.
        - prefix(github.com/freiheit-com/kuberpult) # Your local packages.
      section-separators:
        - newLine # Ensures a newline between the sections above.
