#!/bin/bash
set -eou pipefail
set -x
cd $( dirname "${BASH_SOURCE[0]}" )

docker build -t eu.gcr.io/freiheit-core/kuberpult/build:latest ./docker/build

mkdir -p test
# https://wiki.alpinelinux.org/wiki/Draft_Release_Notes_for_Alpine_3.14.0#faccessat2
exec docker run -it \
  --tmpfs /.cache:rw,noexec,nosuid \
  --mount type=bind,source=$HOME/go,target="/go" \
  --mount type=bind,source="$(pwd)/test",target="/etc/ssh" \
  --mount type=bind,source="$(pwd)",target="/build" \
  -w "/build" \
  --rm \
  -u "$UID" \
  --security-opt=seccomp=default.json \
  -e WITHOUT_DOCKER=true \
  eu.gcr.io/freiheit-core/kuberpult/build:latest "$@"
cd -
