# Here we list all services that we need in order to run unit tests.
# As of now this is only the postgres container

services:
  postgres:
    image: postgres:13.15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=kuberpult
    ports:
      - "5432:5432"
    command: -c config_file=/etc/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 3
