services:
  backend:
    image: ${IMAGE_REGISTRY}/kuberpult-cd-service:${IMAGE_TAG}
    container_name: kuberpult-cd-service
    environment:
      - KUBERPULT_GIT_URL=/repository_remote
      - KUBERPULT_GIT_BRANCH=master
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./services/cd-service/repository_remote:/repository_remote
  # backend:
  #   build: infrastructure/docker/backend
  #   container_name: kuberpult-cd-service
  #   ports:
  #     - "8080:8080"
  #     - "8443:8443"
  #   volumes:
  #     - .:/kp/kuberpult
  frontend:
    image: ${IMAGE_REGISTRY}/kuberpult-frontend-service:${IMAGE_TAG}
    container_name: kuberpult-frontend-service
    environment:
      - KUBERPULT_CDSERVER=kuberpult-cd-service:8443
      - KUBERPULT_HTTP_CD_SERVER=http://kuberpult-cd-service:8080
    ports:
      - "8081:8081"
    depends_on:
      - backend
