services:
  cd:
    image: ${IMAGE_REGISTRY}/kuberpult-cd-service:${IMAGE_TAG_CD}
    container_name: kuberpult-cd-service
    environment:
      - KUBERPULT_GIT_URL=/repository_remote
      - KUBERPULT_GIT_BRANCH=master
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./services/cd-service/repository_remote:/repository_remote
  frontend:
    image: ${IMAGE_REGISTRY}/kuberpult-frontend-service:${IMAGE_TAG_FRONTEND}
    container_name: kuberpult-frontend-service
    environment:
      - KUBERPULT_CDSERVER=kuberpult-cd-service:8443
      - KUBERPULT_ROLLOUTSERVER=kuberpult-rollout-service:8443
      - KUBERPULT_HTTP_CD_SERVER=http://kuberpult-cd-service:8080
      - KUBERPULT_GIT_AUTHOR_NAME="integration tester"
      - KUBERPULT_GIT_AUTHOR_EMAIL="integration.tester@example.com"
    ports:
      - "8081:8081"
    depends_on:
      - cd
