package api

// This file is needed to mark this directory as go package and not fail renovate PRs, the go code here is generally generated by buf and not checked in so renovate thinks this is not a go package
