name: "Pre Build Action"
description: "Runs before build action"
author: "mnishamk-freiheit"
inputs:
  data:
    description: "matrix data used by the build"
    required: true
runs:
  using: "composite"
  steps:
    - id: convert
      shell: sh
      run: |
        echo "::set-output name=data::${{ fromJSON(inputs.data) }}"
    - shell: sh
      run: |
        echo "Pre build action"
    - run: |
        echo "${{ steps.convert.outputs.data }}"
        echo "${{ inputs.data }}"
    - if: contains(steps.convert.outputs.data.preBuildActions, 'check_flag_1') && steps.convert.outputs.data.directory == 'infrastructure/scripts/check-license'
      shell: sh
      run: |
        echo "custom pre build action for chekc-license with variable ${{ steps.convert.outputs.data.name }}"
    # - if: contains(inputs.data.preBuildActions, 'noFlagFound') && inputs.data.directory == 'infrastructure/scripts/check-license'
      # shell: bash
      # run: |
        # echo "can run different shells on different containers"
