name: "Pre Build Action"
description: "Runs before build action"
author: "mnishamk-freiheit"
inputs:
  data:
    description: "matrix data used by the build"
    required: true
runs:
  using: "composite"
  steps:
    - shell: sh
      run: |
        echo "Pre build action"
    - if: contains(data.preBuildActions, 'check_flag_1') && data.directory == 'infrastructure/scripts/check-license'
      shell: sh
      run: |
        echo "custom pre build action for chekc-license with variable ${{ data.name }}"
    - if: contains(data.preBuildActions, 'noFlagFound') && data.directory == 'infrastructure/scripts/check-license'
      shell: bash
      run: |
        echo "can run different shells on different containers"
