VERSION 0.8

source-code:
    FROM golang:1.21.4-alpine3.17

    WORKDIR /kp

    COPY go.mod go.mod
    COPY go.sum go.sum
    COPY pkg pkg
    COPY cmd cmd

test:
    FROM +source-code
    RUN go test ./...

executable:
    FROM +source-code

    RUN mkdir -p bin

    RUN go build -o bin ./...

    SAVE ARTIFACT bin/kuberpult-client

build:
    BUILD +test

    ARG  --required VERSION

    FROM scratch

    COPY +executable/kuberpult-client .

    ENTRYPOINT ["./kuberpult-client"]

    SAVE IMAGE --push europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult/kuberpult-client:${VERSION}

build-pr:
    ARG  --required VERSION

    BUILD +build --VERSION=${VERSION}

build-main:
    ARG  --required VERSION

    BUILD +build --VERSION=${VERSION}