VERSION 0.8

IMPORT ../infrastructure/earthly/go AS go-build

deps:
    FROM golang:1.21.4-alpine3.17

    RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2

    RUN wget https://github.com/GaijinEntertainment/go-exhaustruct/archive/refs/tags/v3.2.0.tar.gz -O exhaustruct.tar.gz
    RUN echo "511d0ba05092386a59dca74b6cbeb99f510b814261cc04b68213a9ae31cf8bf6  exhaustruct.tar.gz" | sha256sum -c
    RUN tar xzf exhaustruct.tar.gz
    WORKDIR go-exhaustruct-3.2.0
    RUN go build ./cmd/exhaustruct
    RUN mv exhaustruct /usr/local/bin/exhaustruct

source-code:
    FROM +deps

    WORKDIR /kp

    COPY go.mod go.mod
    COPY go.sum go.sum
    COPY pkg pkg
    COPY cmd cmd

lint:
    FROM +source-code
    DO go-build+LINT --skip_lint_errors=false
    
test:
    FROM +source-code
    DO go-build+UNIT_TEST

compile:
    FROM +source-code
    DO go-build+COMPILE --main_path=cmd/kuberpult-client

build:
    BUILD +lint
    BUILD +test

    ARG  --required VERSION

    FROM scratch

    COPY +compile/main ./kuberpult-client

    ENTRYPOINT ["./kuberpult-client"]

    SAVE IMAGE --push europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult/kuberpult-client:${VERSION}

build-pr:
    ARG  --required VERSION

    BUILD +build --VERSION=${VERSION}

build-main:
    ARG  --required VERSION

    BUILD +build --VERSION=${VERSION}