VERSION 0.8

IMPORT ../infrastructure/earthly/go AS go-build

deps:
    FROM golang:1.24.2-alpine3.21

    RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.0

    RUN wget https://github.com/GaijinEntertainment/go-exhaustruct/archive/refs/tags/v3.3.1.tar.gz -O exhaustruct.tar.gz
    RUN echo "b9691e2632f00c67a24d0482d0691d1aa51937f6b4a51817478efda4a2ed69d9 exhaustruct.tar.gz" | sha256sum -c
    RUN tar xzf exhaustruct.tar.gz
    WORKDIR go-exhaustruct-3.3.1
    RUN go build ./cmd/exhaustruct
    RUN mv exhaustruct /usr/local/bin/exhaustruct

source-code:
    FROM +deps

    WORKDIR /kp

    COPY go.mod go.mod
    COPY go.sum go.sum
    COPY pkg pkg
    COPY cmd cmd

lint:
    FROM +source-code
    DO go-build+LINT --skip_lint_errors=false
    
test:
    FROM +source-code
    DO go-build+UNIT_TEST

compile:
    FROM +source-code
    DO go-build+COMPILE --main_path=cmd/kuberpult-client

build:
    ARG  --required VERSION

    BUILD +lint
    BUILD +test

    FROM scratch

    COPY +compile/main ./kuberpult-client

    ENTRYPOINT ["./kuberpult-client"]

    SAVE IMAGE --push europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult/kuberpult-client:${VERSION}

build-pr:
    ARG  --required VERSION

    BUILD +build --VERSION=${VERSION}

build-main:
    ARG  --required VERSION

    BUILD +build --VERSION=${VERSION}