---
apiVersion: v1beta1
kind: Service
metadata:
  name: manifest-repo-export-service
  tier: backend
  version: v1
spec:
  stage: Product
  buildWith: infrastructure/docker/builder
  dependsOn:
  - ../../
additional_artifacts:
  - coverage.html
