VERSION 0.8

ARG --global IMAGE_REGISTRY="europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult"
LOCALLY
ARG --global SERVICES=$(ls ../services)

deps:
    FROM alpine:3.18
    WORKDIR /tmp
    ARG TRIVY_VERSION=0.50.1
    ARG TRIVY_CHECKSUM=4cf907dfe770d81931ee56fb996d285edbf4e0d2308bcfd0f4a3d80e93b0f146
	ENV TRIVY_DB_REPOSITORY=fdc-public-docker-registry/generic-artifacts/aquasecurity/trivy-db
    RUN wget "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz"
    RUN echo "${TRIVY_CHECKSUM} trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz" | sha256sum -c
    RUN tar -xzf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz && mv trivy /usr/local/bin/trivy && trivy --version
    WORKDIR /trivy
    COPY templates templates

scan-all:
    FROM +deps
    ARG --required kuberpult_version
    ARG trigger=""
    ARG VERSION_REPORT_NAME="kuberpult-${kuberpult_version}-reports"
    ARG REPORT_TAR_NAME="${VERSION_REPORT_NAME}.tar.gz"
    RUN mkdir $VERSION_REPORT_NAME

    IF [ "$trigger" == "pull-request" ]
        FOR service IN $SERVICES
            BUILD +scan-service-pr --service=$service --version=$kuberpult_version
        END
    ELSE
        FOR service IN $SERVICES
            BUILD +scan-service --service=$service --version=$kuberpult_version
            COPY (+scan-service/* --service=$service --version=$kuberpult_version) $VERSION_REPORT_NAME/
        END
        RUN tar -czf $REPORT_TAR_NAME $VERSION_REPORT_NAME/
        SAVE ARTIFACT $REPORT_TAR_NAME AS LOCAL $REPORT_TAR_NAME
    END

scan-service-pr:
    FROM +deps
    ARG --required service
    ARG --required version
    CACHE --sharing locked --id trivy-cache /tmp/trivy_cache

    RUN trivy --cache-dir /tmp/trivy_cache --severity HIGH,CRITICAL --exit-code 1 image $IMAGE_REGISTRY/kuberpult-$service:$version

scan-service:
    FROM +deps
    ARG --required service
    ARG --required version
    CACHE --sharing locked --id trivy-cache /tmp/trivy_cache

    RUN trivy --cache-dir /tmp/trivy_cache image $IMAGE_REGISTRY/kuberpult-$service:$version -f template --template "@templates/html.tpl" -o kuberpult-$service.html
    SAVE ARTIFACT kuberpult-$service.html

cache-trivy-db:
	FROM +deps
	ARG --required cache_dir
	ARG retries=10
	COPY ./download_db_image.sh .
	RUN  ["/bin/sh", "download_db_image.sh", "$retries", "$cache_dir"]
