ALTER TABLE environments ALTER COLUMN json TYPE VARCHAR;
ALTER TABLE IF EXISTS all_apps ALTER COLUMN json TYPE VARCHAR;
ALTER TABLE all_env_locks ALTER COLUMN json TYPE VARCHAR;
ALTER TABLE all_app_locks ALTER COLUMN json TYPE VARCHAR;