VERSION 0.8

ARG --required --global DOCKER_REGISTRY_URI
ARG --required --global IMAGE_TAG
ARG --required --global VERSION

image:
    FROM DOCKERFILE .

build:
    # duplication since earthly doesn't allow the --global flag with variables defined with LET
    LET IMAGE_NAME=$DOCKER_REGISTRY_URI/infrastructure/docker/git-ssh:$IMAGE_TAG
    LET IMAGE_NAME_VERSIONED=$DOCKER_REGISTRY_URI/infrastructure/docker/builder:$VERSION
    
    FROM +image

    SAVE IMAGE $IMAGE_NAME

build-pr:
    # duplication since earthly doesn't allow the --global flag with variables defined with LET
    LET IMAGE_NAME=$DOCKER_REGISTRY_URI/infrastructure/docker/git-ssh:$IMAGE_TAG
    LET IMAGE_NAME_VERSIONED=$DOCKER_REGISTRY_URI/infrastructure/docker/builder:$VERSION
    
    FROM +image

    SAVE IMAGE --push $IMAGE_NAME
    SAVE IMAGE --push $IMAGE_NAME_VERSIONED

build-main:
    # duplication since earthly doesn't allow the --global flag with variables defined with LET
    LET IMAGE_NAME=$DOCKER_REGISTRY_URI/infrastructure/docker/git-ssh:$IMAGE_TAG
    LET IMAGE_NAME_VERSIONED=$DOCKER_REGISTRY_URI/infrastructure/docker/builder:$VERSION
    
    FROM +image
    
    SAVE IMAGE --push $IMAGE_NAME
    SAVE IMAGE --push $IMAGE_NAME_VERSIONED