name: "Post Build Action"
description: "Runs after build action"
author: "mnishamk-freiheit"
inputs:
  data:
    description: "matrix data used by the build"
    required: true
runs:
  using: "composite"
  steps:
    - shell: sh
      run: |
        echo "Post build action"
    - if: contains(inputs.data.postBuildActions, 'check_flag_1') && inputs.data.directory == 'infrastructure/scripts/check-license'
      shell: sh
      run: |
        echo "custom post build action for chekc-license with variable ${{ inputs.data.name }}"
