metadata:
  name: check-license
  builder: kuberpult-builder
spec:
  buildWith: infrastructure/docker/builder
  dependsOn:
  - ../../..
pre_build_actions:
  - check-license-sample-flag 
post_build_actions:
  - check-license-sample-flag 
