VERSION 0.7

deps:
    FROM ../../+deps
    ARG service
    COPY ../../pkg/api/+artifacts/* pkg/api/
    COPY ../../pkg/auth/+artifacts/* pkg/auth/
    COPY ../../pkg/logger/+artifacts/* pkg/logger/
    COPY ../../pkg/setup/+artifacts/* pkg/setup/
    COPY ../../pkg/tracing/+artifacts/* pkg/tracing/
    COPY ../../pkg/path/+artifacts/* pkg/path/
    COPY pkg services/$service/pkg
    COPY cmd/server/* services/$service/cmd/server/
    RUN apt update && apt install ca-certificates tzdata libgit2-dev git libsqlite3-dev -y
    SAVE ARTIFACT /etc/ssl/certs/ca-certificates.crt
    SAVE ARTIFACT /usr/share/zoneinfo
artifacts:
    FROM +deps
    ARG service
    SAVE ARTIFACT services/$service/pkg
compile:
    FROM +deps
    ARG service
    ARG USERARCH
    WORKDIR services/$service/cmd/server
    RUN CGO_ENABLED=1 \
        GOARCH=$USERARCH \
	    GOOS=linux \
        go build -o bin/main main.go
    SAVE ARTIFACT bin/main
unit-test-deps:
    FROM +deps
    ARG service
    COPY ../../pkg/ptr/+artifacts/* pkg/ptr/
    COPY ../../pkg/testutil/+artifacts/* pkg/testutil/
    COPY ../../pkg/testfs/+artifacts/* pkg/testfs/
unit-test:
    FROM +unit-test-deps
    WORKDIR services/$service
    RUN CGO_ENABLED=1 go test ./...

docker:
    FROM +deps
    ARG UID=1000
    ARG service
    ARG tag="local"
    ARG registry="eu.gcr.io/fdc-standard-setup-dev-env"
    ENV TZ=Europe/Berlin
    RUN useradd -m -d "/kp" --uid ${UID} kp
    RUN chown -R kp:kp /kp
    COPY +compile/main /main
    COPY gitconfig /etc/gitconfig
    USER kp
    WORKDIR /kp
    ENTRYPOINT ["/main"] 
    SAVE IMAGE --cache-from=$registry/services/$service:cache $service:$tag

release:
    FROM +docker
    ARG service
    ARG tag="local"
    ARG registry="eu.gcr.io/fdc-standard-setup-dev-env"
    SAVE IMAGE --push $registry/services/$service:$tag
    SAVE IMAGE --push $registry/services/$service:cache
