apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberpult-migrations
data:
  {{- if and ( .Values.generateMigrations) }}
  {{- range $k, $v := .Files.Glob  "migrations/**.sql" }}
    {{ $k | trimPrefix "migrations/" }}: {{ $.Files.Get $k | toYaml | indent 4 }}
  {{- end }}
  {{- end }}
---

