VERSION 0.7

ARG --required --global DOCKER_REGISTRY_URI
ARG --required --global IMAGE_TAG

image:
    FROM DOCKERFILE .

build:
    # duplication since earthly doesn't allow the --global flag with variables defined with LET
    LET IMAGE_NAME=$DOCKER_REGISTRY_URI/infrastructure/docker/builder:$IMAGE_TAG
    
    FROM +image

    SAVE IMAGE $IMAGE_NAME

build-pr:
    # duplication since earthly doesn't allow the --global flag with variables defined with LET
    LET IMAGE_NAME=$DOCKER_REGISTRY_URI/infrastructure/docker/builder:$IMAGE_TAG
    
    FROM +image

    SAVE IMAGE --push $IMAGE_NAME

build-main:
    # duplication since earthly doesn't allow the --global flag with variables defined with LET
    LET IMAGE_NAME=$DOCKER_REGISTRY_URI/infrastructure/docker/builder:$IMAGE_TAG
    
    FROM +image
    
    SAVE IMAGE --push $IMAGE_NAME
