VERSION 0.8
IMPORT ../infrastructure/earthly/go AS go-build

deps:
    FROM ../+deps
    COPY . pkg/
    RUN cd pkg && buf generate
    SAVE ARTIFACT pkg/api/v1/*.go AS LOCAL api/v1/
artifacts:
    FROM +deps
    SAVE ARTIFACT pkg
lint:
    FROM +deps
    WORKDIR pkg
    RUN buf lint
    DO go-build+LINT --skip_lint_errors=false
test:
    FROM +deps
    ARG GO_TEST_ARGS
    WORKDIR pkg
    RUN go test $GO_TEST_ARGS ./... -coverprofile=coverage.out
    RUN go tool cover -html=coverage.out -o coverage.html
    SAVE ARTIFACT coverage.html AS LOCAL coverage.html

build-all:
    BUILD +lint
    BUILD +test
