VERSION 0.7
IMPORT ../infrastructure/earthly/go AS go-build

deps:
    FROM ../+deps
    COPY . pkg/
    RUN cd pkg && buf generate
    SAVE ARTIFACT pkg/api/v1/*.go AS LOCAL api/v1/
artifacts:
    FROM +deps
    SAVE ARTIFACT pkg
lint:
    FROM +deps
    WORKDIR pkg
    RUN buf lint
    DO go-build+LINT --skip_lint_errors=false
test:
    FROM +deps
    ARG GO_TEST_ARGS
    WORKDIR pkg
    RUN go test $GO_TEST_ARGS ./...
build-all:
    BUILD +lint
    BUILD +test
