VERSION 0.7
ARG --global service=rollout-service

deps:
    FROM ../../+deps
    RUN apt update && apt install ca-certificates tzdata -y
    COPY ../../pkg+artifacts/* pkg/
    COPY pkg services/$service/pkg
    COPY cmd/server/* services/$service/cmd/server/
    COPY (../cd-service/+artifacts/pkg --service=cd-service) services/cd-service/pkg/
    SAVE ARTIFACT /etc/ssl/certs/ca-certificates.crt
    SAVE ARTIFACT /usr/share/zoneinfo
    SAVE IMAGE --cache-hint
artifacts:
    FROM +deps
    SAVE ARTIFACT services/$service/pkg
compile:
    FROM +deps
    ARG USERARCH
    WORKDIR services/$service/cmd/server
    RUN CGO_ENABLED=0 \
        GOARCH=$USERARCH \
	    GOOS=linux \
        go build -o bin/main main.go
    SAVE ARTIFACT bin/main
    SAVE IMAGE --cache-hint

unit-test:
    FROM +deps
    WORKDIR services/$service
    RUN CGO_ENABLED=0 go test ./...

docker:
    FROM alpine:3.18
    ARG UID=1000
    ARG tag="local"
    ENV TZ=Europe/Berlin
    RUN adduser -D -h "/kp" --uid ${UID} kp
    RUN chown -R kp:kp /kp
    COPY +compile/main /main
    COPY +deps/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
    COPY +deps/zoneinfo /usr/share/zoneinfo
    USER kp
    WORKDIR /kp
    ENTRYPOINT ["/main"] 
    SAVE IMAGE $service:$tag

release:
    FROM +docker
    ARG tag="local"
    ARG registry="ghcr.io/freiheit-com/kuberpult"
    SAVE IMAGE --push $registry/kuberpult-$service:$tag
