VERSION 0.7
IMPORT ../../infrastructure/earthly/go AS go-build

LOCALLY
ARG --global service=$(basename $PWD)
ARG --global UID=1000
ARG --global cgo_enabled=0
ARG --global registry="europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult"
ARG --global tag="local"

deps:
    FROM ../../+deps
    DO go-build+DEPS --service=$service
    COPY (../cd-service/+artifacts/pkg --service=cd-service) /kp/services/cd-service/pkg/
    WORKDIR services/$service

artifacts:
    FROM +deps
    SAVE ARTIFACT /etc/ssl/certs/ca-certificates.crt
    SAVE ARTIFACT /usr/share/zoneinfo

compile:
    FROM +deps
    DO go-build+COMPILE --cgo_enabled=$cgo_enabled

unit-test:
    FROM +compile
    DO go-build+UNIT_TEST
    
docker:
    FROM ../../+base-image
    COPY +artifacts/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
    COPY +artifacts/zoneinfo /usr/share/zoneinfo
    COPY +compile/main /main

    DO go-build+DOCKER --UID=$UID --image_tag=$registry/kuberpult-$service:$tag --entry_point=/main

release:
    FROM +docker
    DO go-build+RELEASE --image_tag=$registry/kuberpult-$service:$tag