VERSION 0.7
IMPORT ../../infrastructure/earthly/go AS go-build

LOCALLY
ARG --global service=$(basename $PWD)
ARG --global UID=1000
ARG --global cgo_enabled=0

deps:
    FROM ../../+deps
    DO go-build+DEPS --service=$service
    COPY (../cd-service/+artifacts/pkg --service=cd-service) /kp/services/cd-service/pkg/
    WORKDIR services/$service

artifacts:
    FROM +deps
    SAVE ARTIFACT /etc/ssl/certs/ca-certificates.crt
    SAVE ARTIFACT /usr/share/zoneinfo

compile:
    FROM +deps
    DO go-build+COMPILE --cgo_enabled=$cgo_enabled

unit-test:
    FROM +compile
    DO go-build+UNIT_TEST
    
docker:
    FROM alpine:3.18
    ARG registry="europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult"
    ARG tag="local"
    DO go-build+DOCKER --UID=$UID --image_tag=$registry/kuberpult-$service:$tag --entry_point=/main --cgo_enabled=$cgo_enabled --service=$service

release:
    FROM +docker
    ARG registry="europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult"
    ARG --required tag
    DO go-build+RELEASE --image_tag=$registry/kuberpult-$service:$tag