name: "Kuberpult Trivy Caching"
on:
  pull_request:
    branches:
      - 'main'
  # schedule:
  #   - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest
    env:
      CACHE_REGISTRY: europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install earthly
      uses: earthly/actions-setup@v1
      with:
          version: v0.8.13

    - name: Install trivy
      run: |
        cd trivy
        earthly +deps

    # - name: Install Trivy
    #   uses: aquasecurity/setup-trivy@v0.2.2
    #   with:
    #     version: v0.56.2
      #
          
    - name: Login to Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: europe-west3-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_ARTIFACT_REGISTRY_PUSH_JSON_KEY }}

    - name: Download and push trivy image
      run: |
        TRIVY_TEMP_DIR=$(mktemp -d)
        trivy --cache-dir $TRIVY_TEMP_DIR image --download-db-only

        gcloud artifacts generic upload \
          --location=europe-west3 \
          --project=fdc-public-docker-registry \
          --repository=kuberpult \
          --package=trivy-db-cache \
          --source-directory=$TRIVY_TEMP_DIR/db \
          --version=1
