name: "Kuberpult Trivy Caching"
on:
  pull_request:
    branches:
      - 'main'
  # schedule:
  #   - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest
    env:
      CACHE_REGISTRY: europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult
      LOCAL_CACHE: /trivy_db_cache
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install earthly
      uses: earthly/actions-setup@v1
      with:
          version: v0.8.13

    - name: Cache trivy
      run: |
        cd trivy
        mkdir $LOCAL_CACHE
        earthly +cache-trivy-db --cache_dir $LOCAL_CACHE
          
    - name: Login to Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: europe-west3-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_ARTIFACT_REGISTRY_PUSH_JSON_KEY }}

    - name: Push trivy image
      run: |
        gcloud artifacts generic upload \
          --location=europe-west3 \
          --project=fdc-public-docker-registry \
          --repository=kuberpult \
          --package=trivy-db-cache \
          --source-directory=$LOCAL_CACHE/db \
          --version=1
