name: "Kuberpult Trivy Caching"
on:
  pull_request:
    branches:
      - 'main'
  # schedule:
  #   - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      LOCAL_CACHE: ./trivy_db_cache
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install earthly
      uses: earthly/actions-setup@v1
      with:
          version: v0.8.13

    - uses: google-github-actions/auth@v2
      name: "Authenticate to Google Cloud"
      with:
        credentials_json: '${{ secrets.GCP_ARTIFACT_REGISTRY_PUSH_JSON_KEY }}'

    # - name: Add credentials file
    #   run: |
    #     cat > credential.json << EOF
    #     ${{ secrets.GCP_ARTIFACT_REGISTRY_PUSH_JSON_KEY }}
    #     EOF

    - name: Cache trivy
      run: |
        cd trivy
        earthly +cache-trivy-db --cache_dir $LOCAL_CACHE
        gcloud artifacts generic upload \
          --location=europe-west3 \
          --project=fdc-public-docker-registry \
          --repository=kuberpult-generic \
          --destination-path=aquasecurity \
          --package=trivy-db \
          --source-directory=$LOCAL_CACHE/db \
          --version=2.0.0
