name: "Kuberpult Trivy Caching"
on:
  pull_request:
    branches:
      - 'main'
  # schedule:
  #   - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      LOCAL_CACHE: ./trivy_db_cache
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install earthly
      uses: earthly/actions-setup@v1
      with:
          version: v0.8.13

    - uses: google-github-actions/auth@v2
      name: "Authenticate to Google Cloud"
      with:
        credentials_json: ${{ secrets.FDC_CORE_CI_IMAGE_READER }}

    - name: gcloud authorize
      run: |
        gcloud auth configure-docker
          
    - name: Add credentials file
      run: |
        cat > credential.json << EOF
        ${{ secrets.GCP_ARTIFACT_REGISTRY_PUSH_JSON_KEY }}
        EOF

    - name: Login to Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: europe-west3-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_ARTIFACT_REGISTRY_PUSH_JSON_KEY }}

    - name: Cache trivy
      run: |
        cd trivy
        earthly +cache-trivy-db --cache_dir $LOCAL_CACHE
        gcloud artifacts generic upload \
          --location=europe-west3 \
          --project=fdc-public-docker-registry \
          --repository=kuberpult-generic \
          --package=aquasecurity/trivy-db \
          --source-directory=$LOCAL_CACHE/db \
          --version=1 \
          --access-token-file=credential.json
