name: "Execution Plan on Pull Request"
'on':
  pull_request:
    branches:
      - main
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0
    - name: Run license checking script
      run: |
        sh check.sh