name: Test CI Realibility

on:
  schedule:
    # Run on workdays at 8:00 AM
    - cron: '0 8 * * 1-5'
  workflow_call:
    inputs:
      base_branch:
        required: false
        default: main
        type: string
      source_branch:
        required: true
        type: string

      # enable services to be modified
      modify_cd_service:
        required: false
        default: false
        type: boolean
      modify_frontend_service:
        required: false
        default: false
        type: boolean
      modify_export_service:
        required: false
        default: false
        type: boolean
      modify_pkg:
        required: false
        default: false
        type: boolean
      
      # enable image checks for services
      check_image_cd_service:
        required: false
        default: false
        type: boolean
      check_image_frontend_service:
        required: false
        default: false
        type: boolean
      check_image_export_service:
        required: false
        default: false
        type: boolean

jobs:
  # introduce-changes:
  #   name: Introduce changes
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #       with:
  #         fetch-depth: 0
  #     - name: Prepare testing branch
  #       run: |
  #         # delete existing testing branch
  #         git push origin --delete ${{ inputs.source_branch }} || true

  #         # create testing branch with changes
  #         git checkout ${{ inputs.base_branch }}
  #         git checkout -b ${{ inputs.source_branch }}
  #     - name: Modify pkg
  #       if: inputs.modify_pkg == true
  #       run: |
  #         echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> pkg/api/api.go
  #     - name: Modify cd-service
  #       if: inputs.modify_cd_service == true
  #       run: |
  #         echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> services/cd-service/cmd/server/main.go
  #     - name: Modify frontend-service
  #       if: inputs.modify_frontend_service == true
  #       run: |
  #         echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> services/frontend-service/cmd/server/main.go
  #     - name: Modify export-service
  #       if: inputs.modify_export_service == true
  #       run: |
  #         echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> services/manifest-repo-export-service/cmd/server/main.go
  #     - name: Commit changes
  #       run: |
  #         git config user.name "github-actions[bot]"
  #         git config user.email "github-actions[bot]@users.noreply.github.com"
  #         git add .
  #         git commit -m "Automated: Test CI realibility for ${{ inputs.source_branch }}"
  #         git push origin ${{ inputs.source_branch }}
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # trigger-ci:
  #   name: Trigger CI build with specific ref
  #   needs: [introduce-changes]
  #   uses: ./.github/workflows/execution-plan-snippet.yml
  #   with:
  #     trigger: pull-request
  #     ref: ${{ inputs.source_branch }}
  #     skip_unversioned_builds: true
  #   secrets: inherit
  check-built-image:
    name: "Check built image on registry"
    # needs: [trigger-ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.source_branch }}
      - uses: warjiang/setup-skopeo@main
        with:
          version: latest
      - name: Set image tag
        run: |
          IMAGE_TAG="pr-$(make version)"
          echo "Published image tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Check built image for cd-service
        run: |
          IMAGE_TAG="pr-v13.44.13-1-gbc6b7947"
          IMAGE_NAME="europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult/kuberpult-cd-service"
          [[ "$(skopeo inspect -f '{{.Digest}}' docker://$IMAGE_NAME:main" == "$(skopeo inspect -f '{{.Digest}}' docker://$IMAGE_NAME:$IMAGE_TAG)" ]] && echo "Identical" || echo "Different"
          
        
          
        
