name: Test CI Reliability

on:
  workflow_call:
    inputs:
      test_id:
        required: true
        type: string
        description: "Unique ID used for naming artifact"
      base_branch:
        required: false
        default: main
        type: string
        description: "The base branch from which the source branch is created."
      source_branch:
        required: true
        type: string
        description: "The source branch must follow this format: automated/ci-reliability/ci-test-<no>."

      # enable services to be modified
      modify_cd_service:
        required: true
        type: boolean
      modify_frontend_service:
        required: true
        type: boolean
      modify_export_service:
        required: true
        type: boolean
      modify_pkg:
        required: true
        type: boolean
      
      # enable checks: verify if new images is built for services
      expect_new_image_cd_service:
        required: true
        type: boolean
      expect_new_image_frontend_service:
        required: true
        type: boolean
      expect_new_image_export_service:
        required: true
        type: boolean

jobs:
  introduce-changes:
    name: Introduce changes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Prepare testing branch
        run: |
          # delete existing testing branch
          git push origin --delete ${{ inputs.source_branch }} || true

          # create testing branch with changes
          git checkout ${{ inputs.base_branch }}
          git checkout -b ${{ inputs.source_branch }}
      - name: Modify pkg
        if: inputs.modify_pkg == true
        run: |
          echo -e "\nfunc TestCIReliability_$(date +%s%6N)() {}" >> pkg/api/api.go
      - name: Modify cd-service
        if: inputs.modify_cd_service == true
        run: |
          echo -e "\nfunc TestCIReliability_$(date +%s%6N)() {}" >> services/cd-service/cmd/server/main.go
      - name: Modify frontend-service
        if: inputs.modify_frontend_service == true
        run: |
          echo -e "\nfunc TestCIReliability_$(date +%s%6N)() {}" >> services/frontend-service/cmd/server/main.go
      - name: Modify export-service
        if: inputs.modify_export_service == true
        run: |
          echo -e "\nfunc TestCIReliability_$(date +%s%6N)() {}" >> services/manifest-repo-export-service/cmd/server/main.go
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated: Test CI Reliability for ${{ inputs.source_branch }}" || echo "No changes to commit"
          git push origin ${{ inputs.source_branch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  trigger-ci:
    name: Trigger CI build with specific ref
    needs: [introduce-changes]
    uses: ./.github/workflows/execution-plan-snippet.yml
    with:
      trigger: pull-request
      ref: ${{ inputs.source_branch }}
      skip_unversioned_builds: true
      run_id: ${{ inputs.test_id }}
    secrets: inherit
  check-new-images:
    name: "Check newly built images on registry"
    needs: [trigger-ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.source_branch }}
      - uses: warjiang/setup-skopeo@main
        with:
          version: latest
      - name: Set image tag
        run: |
          IMAGE_TAG="pr-$(make version)"
          echo "Published image tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Check newly built image for cd-service
        id: check-cd-service
        uses: ./.github/actions/check-image-build
        with:
          service_name: "cd-service"
          expect_new_image: ${{ inputs.expect_new_image_cd_service }}
      - name: Check newly built image for frontend-service
        id: check-frontend-service
        uses: ./.github/actions/check-image-build
        with:
          service_name: "frontend-service"
          expect_new_image: ${{ inputs.expect_new_image_frontend_service }}
      - name: Check newly built image for manifest-repo-export-service
        id: check-manifest-repo-export-service
        uses: ./.github/actions/check-image-build
        with:
          service_name: "manifest-repo-export-service"
          expect_new_image: ${{ inputs.expect_new_image_export_service }}
      - name: Create validation errors artifact
        run: |
          echo "${{ steps.check-cd-service.outputs.validation_errors }}" >> validation-errors.txt
          echo "${{ steps.check-frontend-service.outputs.validation_errors }}" >> validation-errors.txt
          echo "${{ steps.check-manifest-repo-export-service.outputs.validation_errors }}" >> validation-errors.txt
      - name: Upload validation errors
        id: upload-validation-errors
        uses: actions/upload-artifact@v6
        with:
          name: validation-errors-${{ inputs.test_id }}.zip
          path: validation-errors.txt
