name: ci-realibilty

on:
  schedule:
    # Run on workdays at 8:00 AM
    - cron: '0 8 * * 1-5'
  push:
    branches:
      - db-prtest

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          title: "DO NOT MERGE: Testing CI realibility for cd-service"
          commit-message: "Testing CI realibility for cd-service"
          branch: "automated/ci-realibility/cd-service"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          delete-branch: false

        
