name: Test CI Reliability

on:
  schedule:
    # Run on workdays at 8:00 AM
    - cron: '0 8 * * 1-5'
  push:
    branches:
      - db-citest

jobs:
  ci-test-1:
    name: Test CI Reliability for cd-service
    uses: ./.github/workflows/ci-reliability-snippet.yml
    with:
      source_branch: automated/ci-reliability/ci-test-1
      modify_cd_service: false
      check_new_image_cd_service: false
    secrets: inherit
  notify-results:
    name: Notify results
    needs: [ci-test-1]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify results
        run: |
          EMOJI_RESULT_OVERALL="✅"
          EMOJI_RESULT_CI_TEST_1="✅"
          if [[ "${{ needs.ci-test-1.result }}" != "success" ]] || [[ -n "${{ needs.ci-test-1.outputs.failed_results }}" ]]; then
            EMOJI_RESULT_CI_TEST_1="❌"
            EMOJI_RESULT_OVERALL="❌"
          fi

          MSG="*CI Reliability Test $EMOJI_RESULT_OVERALL*"
          MSG+="\n\n*Test:* \`ci-test-1\` $EMOJI_RESULT_CI_TEST_1 (cd-service)"
          if [ -n "${{ needs.ci-test-1.outputs.failed_results }}" ]; then
            MSG+="\n\`\`\`${{ needs.ci-test-1.outputs.failed_results }}\n\`\`\`"
          fi

          echo $MSG

          # curl \
          #   --request POST \
          #   --header "Content-Type: application/json" \
          #   --data "{\"text\": \"$MSG\"}" \
          #   --fail \
          #   "${{ secrets.SLACK_WEBHOOK_SRE_ALERTS_INTERNAL }}"
