name: Test CI Reliability 3

on:
  schedule:
    # Run on workdays at 8:00 AM
    - cron: '0 8 * * 1-5'

jobs:
  ci-test-3:
    name: Test CI Reliability for all services
    uses: ./.github/workflows/ci-reliability-snippet.yml
    with:
      source_branch: automated/ci-reliability/ci-test-3
      modify_pkg: true
      check_new_image_cd_service: true
      check_new_image_frontend_service: true
      check_new_image_export_service: true
    secrets: inherit
  notify-results:
    name: Notify results
    needs: [ci-test-3]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify results
        run: |
          EMOJI_RESULT_OVERALL="✅"
          EMOJI_RESULT_CI_TEST_3="✅"
          VALIDATION_ERRORS_CI_TEST_3="${{ needs.ci-test-3.outputs.failed_results }}"
          if [[ "${{ needs.ci-test-3.result }}" != "success" ]] || [[ -n "$VALIDATION_ERRORS_CI_TEST_3" ]]; then
            EMOJI_RESULT_CI_TEST_3="❌"
            EMOJI_RESULT_OVERALL="❌"
          fi

          if [[ "${{ needs.ci-test-3.result }}" != "success" ]]; then
            VALIDATION_ERRORS_CI_TEST_3="\nError occurred during CI test"
          fi

          MSG="*CI Reliability Test $EMOJI_RESULT_OVERALL*"
          MSG+="\n\n*Test:* \`ci-test-3\` $EMOJI_RESULT_CI_TEST_3 (all services)"
          if [ -n "$VALIDATION_ERRORS_CI_TEST_3" ]; then
            MSG+="\n\`\`\`$VALIDATION_ERRORS_CI_TEST_3\n\`\`\`"
          fi

          curl \
            --request POST \
            --header "Content-Type: application/json" \
            --data "{\"text\": \"$MSG\"}" \
            --fail \
            "${{ secrets.SLACK_WEBHOOK_SRE_ALERTS_INTERNAL }}"
