name: Test CI Reliability

on:
  schedule:
    # Run on workdays at 8:00 AM
    - cron: '0 8 * * 1-5'
  push:
    branches:
      - db-citest

jobs:
  ci-test:
    name: Test CI Reliability (${{ matrix.id }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: "1" # test change in cd-service
            source_branch: automated/ci-reliability/ci-test-1
            modify_pkg: false
            modify_cd: false
            check_cd: false
            modify_fe: false
            check_fe: false
            modify_export: false
            check_export: false
          - id: "2" # test change in frontend-service and manifest-repo-export-service
            source_branch: automated/ci-reliability/ci-test-2
            modify_pkg: false
            modify_cd: false
            check_cd: false
            modify_fe: false
            check_fe: false
            modify_export: false
            check_export: false
          # - id: "3" # test change in pkg
          #   source_branch: automated/ci-reliability/ci-test-3
          #   modify_pkg: true
          #   modify_cd: true
          #   check_cd: true
          #   modify_fe: true
          #   check_fe: true
          #   modify_export: true
          #   check_export: true
    uses: ./.github/workflows/ci-reliability-snippet.yml
    with:
      test_id: ${{ matrix.id }}
      source_branch: ${{ matrix.source_branch }}
      modify_pkg: ${{ matrix.modify_pkg }}
      modify_cd_service: ${{ matrix.modify_cd }}
      check_new_image_cd_service: ${{ matrix.check_cd }}
      modify_frontend_service: ${{ matrix.modify_fe }}
      check_new_image_frontend_service: ${{ matrix.check_fe }}
      modify_export_service: ${{ matrix.modify_export }}
      check_new_image_export_service: ${{ matrix.check_export }}
    secrets: inherit
  notify-results:
    name: Notify results
    needs: [ci-test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download validation errors for Test 1
        uses: actions/download-artifact@v6
        with:
          name: validation-errors-1.zip
          path: validation-errors-1
      # - name: Download validation errors for Test 2
      #   uses: actions/download-artifact@v6
      #   with:
      #     name: validation-errors-2.zip
      #     path: validation-errors-2
      # - name: Download validation errors for Test 3
      #   uses: actions/download-artifact@v6
      #   with:
      #     name: validation-errors-3.zip
      #     path: validation-errors-3
      - name: Notify results
        run: |
          EMOJI_RESULT_OVERALL="✅"
          EMOJI_RESULT_CI_TEST_1="✅"
          EMOJI_RESULT_CI_TEST_2="✅"
          
          VALIDATION_ERRORS_CI_TEST_1="$(cat validation-errors-1/validation-errors.txt)"
          VALIDATION_ERRORS_CI_TEST_2="$(cat validation-errors-2/validation-errors.txt)"
          echo "Validation errors 1: $VALIDATION_ERRORS_CI_TEST_1"
          echo "Validation errors 2: $VALIDATION_ERRORS_CI_TEST_2"

          # if [[ "${{ needs.ci-test.result }}" != "success" ]] || [[ -n "$VALIDATION_ERRORS_CI_TEST_1" ]]; then
          #   EMOJI_RESULT_CI_TEST_1="❌"
          #   EMOJI_RESULT_OVERALL="❌"
          # fi

          # if [[ "${{ needs.ci-test.result }}" != "success" ]]; then
          #   VALIDATION_ERRORS_CI_TEST_1="\nError occurred during CI test"
          # fi

          # MSG="*CI Reliability Test $EMOJI_RESULT_OVERALL*"
          # MSG+="\n\n*Test:* \`ci-test-1\` $EMOJI_RESULT_CI_TEST_1 (cd-service)"
          # if [ -n "$VALIDATION_ERRORS_CI_TEST_1" ]; then
          #   MSG+="\n\`\`\`$VALIDATION_ERRORS_CI_TEST_1\n\`\`\`"
          # fi

          # echo -e $MSG

          # curl \
          #   --request POST \
          #   --header "Content-Type: application/json" \
          #   --data "{\"text\": \"$MSG\"}" \
          #   --fail \
          #   "${{ secrets.SLACK_WEBHOOK_SRE_ALERTS_INTERNAL }}"
