name: Test CI Realibility

on:
  schedule:
    # Run on workdays at 8:00 AM
    - cron: '0 8 * * 1-5'
  push:
    branches:
      - db-prtest

jobs:
  test-cd-service:
    name: Test CI realibility for cd-service
    uses: ./.github/workflows/ci-realibilty-snippet.yml
    with:
      source_branch: automated/ci-realibility/cd-service
      modify_cd_service: true
      check_image_cd_service: true
    secrets: inherit
