name: "Codereviewr Check"

on:
  pull_request:
    branches:
      - main

jobs:
  known_filenames:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0 # Since codereviewer wants to analyse the whole pull-request.
    - name: Codereviewr Download
      env:
        CODE_REVIEWER_LOCATION: ${{ github.workspace }}/bin
      run: make analyze/download
    - name: Codereviewr Filename Check
      env:
        FROM: ${{ github.event.pull_request.base.sha }}
        CODE_REVIEWER_LOCATION: ${{ github.workspace }}/bin
      run: |
        echo "analysing since commit '$FROM'"
        make analyze/pull-request
