name: Enforce commit linting

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
            version: v0.8.13
      - name: Lint commit message
        run: |
          make commitlint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
