name: "Frontend test-format"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run front end tests
    runs-on: ubuntu-latest
    script: "cd services/frontend-service/"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
      - run: yarn --frozen-lockfile
      - run: yarn run build
      - run: yarn run test
      - run: yarn eslint