name: Release kuberpult with semantic versioning
on:
  workflow_dispatch:

jobs:
  release:
    name: Release kuberpult with semantic versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Identify version to create
        uses: go-semantic-release/action@v1
        id: semrel-version
        with:
          dry: true
          ghr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create helm chart for release
        run: |
          make -C charts/kuberpult release-tag VERSION=${{ steps.semrel-version.outputs.version }}
      - name: Create release
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: "emojis=true"
      - name: Append helm chart to release
        run: |
          echo $VERSION
          gh release upload v$VERSION charts/kuberpult/kuberpult-$VERSION.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.semrel.outputs.version }}
