name: "Helm Test"
on:
  workflow_call:
    inputs:
      imageTagPrefix:
        description: 'Either "pr-" or "main-"'
        required: true
        type: string

jobs:
  run-helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run helm chart tests
        run: |
          IMAGE_TAG_KUBERPULT="${{ inputs.imageTagPrefix }}$(make version)" make -C charts/kuberpult test-helm
