name: "Helm Test"
on:
  workflow_call:

jobs:
  run-helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref || '' }}
      - name: Run helm chart tests
        run: |
          IMAGE_TAG_KUBERPULT="$(make pr-version)" make -C charts/kuberpult test-helm
