name: docker-build-test
'on':
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    container:
      image: europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult/kuberpult-dependencies:0.1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make .install
      - name: Run tests
        env:
          LD_LIBRARY_PATH: '/usr/local/lib'
        run: make test
