name: Lint and Test Charts

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "Version tag of the kuberpult service images to be installed" 

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Set version
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
 
      - name: Create chart and test values
        run: |
          make -C charts/kuberpult ci/test-values.yaml

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main --all

      - name: Helm linting
        run: |
          make -C charts/kuberpult test-ci

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --debug --target-branch main --helm-extra-args " --timeout 1m "
