name: "Trivy secret scanning"
on:
  push:
    branches:
    - "*"
  pull_request:
jobs:
  scan:
    name: "Trivy scan in fs mode"
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.21.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        scanners: 'secret'
        exit-code: '1'
      env:
        TRIVY_SECRET_CONFIG: 'trivy/trivy-secret.yaml'
  send-alert:
    name: "Send alert in case secret is detected"
    if: ${{ failure() }}
    needs: scan
    runs-on: ubuntu-22.04
    steps:
    - name: Run curl to the Slack webhook
      run: |
        curl ${{ secrets.SLACK_WEBHOOK_SRE_ALERTS_INTERNAL }}